[package]
name = "np_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
np_base = { path = "../np_base" }
tokio = { version = "1", features = ["full"] }
log = "0.4.0"
env_logger = "0.10.0"
lazy_static = { version = "1.4.0", features = [] }
bytes = { version = "1", features = [] }
byteorder = "1.5.0"
prost = "0.12"

[dev-dependencies]
