[package]
name = "np_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
np_base = {path = "../np_base" }
tokio = { version = "1", features = ["full"] }
log = "0.4.0"


[dev-dependencies]
env_logger = "0.10.0"
