[package]
name = "np_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
np_base = {path = "../np_base"}
np_proto = {path = "../np_proto"}
tokio = { version = "1", features = ["full"] }