[package]
name = "np_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
np_base = {path = "../np_base"}
np_proto = {path = "../np_proto"}
tokio = { version = "1", features = ["full"] }
log = { version = "0.4.0", features = [] }
env_logger = "0.10.1"
time = "0.3.30"
bytes = { version = "1", features = [] }
byteorder = "1.5.0"
prost = "0.12"