[package]
name = "np_base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { version = "1.5.0", features = [] }
tokio = { version = "1", features = ["full"] }
log = "0.4.0"
async-trait = "0.1.75"
byteorder = "1.5.0"



