[package]
name = "np_base"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.12"
regex = "1.10.2"
bytes = { version = "1.5.0", features = [] }
heck = "0.3.3"

[build-dependencies]
prost-build = "0.12"
protoc-prebuilt = "0.2.0"
regex = "1"
heck = "0.4"


