name: build_for_linux

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install musl-tools -y
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl

    - name: Install Rust-wasm
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: wasm32-unknown-unknown
        toolchain: 1.76.0
        override: true
        
    - name: Build web
      id: build_web
      run: |
        cd ../
        git clone https://github.com/tkzcfc/npipe_web.git
        cd npipe_web
        rustup target add wasm32-unknown-unknown
        cargo install --locked trunk
        trunk build --release
        cd ../
        mkdir -p release
        cp -r ./npipe_web/dist/ ./release/
        cd release
        tar -czvf npipe.tar.gz *
        cd ../
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./release/npipe.tar.gz
